apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-manager-ui-ingress
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - project-manager.jannekeipert.de
      secretName: multi-domain-cert
  rules:
    - host: project-manager.jannekeipert.de
      http:
        paths:
          - backend:
              service:
                name: project-manager-ui
                port:
                  number: 80
            path: /
            pathType: Prefix
